FROM --platform=arm64 ubuntu:jammy-20240911.1 

RUN apt-get update && apt-get install -y wget git cmake
RUN wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/sbsa/cuda-keyring_1.1-1_all.deb && \ 
    dpkg -i cuda-keyring_1.1-1_all.deb && \
    apt-get update && \
    apt-get install -y cuda-toolkit-12-4 nvidia-headless-550-open 

ENV LLAMACPP_TAG=b4382
ENV LLAMACPP_GPU=true

ADD build.sh /
CMD ["/bin/sh", "-c", "/build.sh"]

