FROM nvidia/cuda:12.4.1-cudnn-devel-ubuntu22.04

RUN apt-get update && apt-get install -y git cmake nvidia-headless-550 curl libcurl4-openssl-dev

ADD entrypoint.sh /
CMD ["/bin/sh", "-c", "/entrypoint.sh"]

